#!/bin/zsh
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# Personal Zsh configuration file. It is strongly recommended to keep all
# shell customization and configuration (including exported environment
# variables such as PATH) in this file or in files sourced from it.
#
# Documentation: https://github.com/romkatv/zsh4humans/blob/v5/README.md.
# Periodic auto-update on Zsh startup: 'ask' or 'no'.
# You can manually run `z4h update` to update everything.
zstyle ':z4h:' auto-update 'yes'
# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
zstyle ':z4h:' auto-update-days '14'

# Keyboard type: 'mac' or 'pc'.
zstyle ':z4h:bindkey' keyboard 'mac'

# Don't start tmux.
zstyle ':z4h:' start-tmux no

# Mark up shell's output with semantic information.
zstyle ':z4h:' term-shell-integration 'yes'

# Right-arrow key accepts one character ('partial-accept') from
# command autosuggestions or the whole thing ('accept')?
zstyle ':z4h:autosuggestions' forward-char 'accept'

# Recursively traverse directories when TAB-completing files.
zstyle ':z4h:fzf-complete' recurse-dirs 'no'

# Enable direnv to automatically source .envrc files.
zstyle ':z4h:direnv' enable 'yes'
# Show "loading" and "unloading" notifications from direnv.
zstyle ':z4h:direnv:success' notify 'yes'

# Enable ('yes') or disable ('no') automatic teleportation of z4h over
# SSH when connecting to these hosts.
zstyle ':z4h:ssh:example-hostname1' enable 'yes'
zstyle ':z4h:ssh:*.example-hostname2' enable 'no'
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*' enable 'no'

# Send these files over to the remote host when connecting over SSH to the
# enabled hosts.
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh' '~/.colors.zsh' '~/.alias.zsh'

# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `z4h init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
z4h install ohmyzsh/ohmyzsh || return                      # ohmyzsh as i use a few plugins from it
z4h install conda-incubator/conda-zsh-completion || return # 🐍 completions for conda & mamba
z4h install clarketm/zsh-completions || return             # a compliation of a lot of zsh completions
z4h install MichaelAquilina/zsh-you-should-use || return   # reminds me about aliases I've setup
z4h install mroth/evalcache || return                      # evalcache too
z4h install cowboyd/zsh-volta || return                    # volta toolchain

# Install or update core components (fzf, zsh-autosuggestions, etc.) and
# initialize Zsh. After this point console I/O is unavailable until Zsh
# is fully initialized. Everything that requires user interaction or can
# perform network I/O must be done above. Everything else is best done below.
z4h init || return

# Source additional local environment files.
z4h source ~/.colors.zsh
z4h source ~/.env.zsh

# Load Anaconda
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOMEBREW_PREFIX/Caskroom/mambaforge/base/bin/conda' 'shell.zsh' 'hook' 2>/dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOMEBREW_PREFIX/Caskroom/mambaforge/base/etc/profile.d/conda.sh" ]; then
        . "$HOMEBREW_PREFIX/Caskroom/mambaforge/base/etc/profile.d/conda.sh"
    else
        export PATH="$HOMEBREW_PREFIX/Caskroom/mambaforge/base/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "$HOMEBREW_PREFIX/Caskroom/mambaforge/base/etc/profile.d/mamba.sh" ]; then
    . "$HOMEBREW_PREFIX/Caskroom/mambaforge/base/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

# Use additional Git repositories pulled in with `z4h install`.
z4h load -c ohmyzsh/ohmyzsh/plugins/git          # load git plugin
z4h load -c ohmyzsh/ohmyzsh/plugins/golang       # load go-lang plugin
z4h load -c ohmyzsh/ohmyzsh/plugins/vscode       # load vscode plugin
z4h load -c ohmyzsh/ohmyzsh/plugins/macos        # load macos plugin
z4h load -c ohmyzsh/ohmyzsh/plugins/composer     # load composer plugin
z4h load -c conda-incubator/conda-zsh-completion # load anaconda-completions
z4h load -c clarketm/zsh-completions             # load extended completions
z4h load -c MichaelAquilina/zsh-you-should-use   # load abbr reminders
z4h load -c mroth/evalcache                      # load eval chacher
z4h load -c cowboyd/zsh-volta                    # load volta toolchain
z4h load -c ohmyzsh/ohmyzsh/plugins/magic-enter  # magic enter plugin

# tea hook for zsh
add-zsh-hook -Uz chpwd(){ source <(tea -Eds) }  #tea

# tabtab for pnpm
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true # pnpm completions using their modified tabtab

z4h source ~/.alias.zsh # load aliases

# Define key bindings.
z4h bindkey undo Ctrl+/ Shift+Tab # undo the last command line change
z4h bindkey redo Option+/         # redo the last undone command line change

z4h bindkey z4h-cd-back Shift+Left     # cd into the previous directory
z4h bindkey z4h-cd-forward Shift+Right # cd into the next directory
z4h bindkey z4h-cd-up Shift+Up         # cd into the parent directory
z4h bindkey z4h-cd-down Shift+Down     # cd into a child directory

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots    # no special treatment for file names with a leading dot
setopt no_auto_menu # require an extra TAB press to open the completion menu

# External Loaders
completion_cacher chezmoi "chezmoi completion zsh"
completion_cacher railway "railway completion zsh"
completion_cacher volta "volta completions zsh"
completion_cacher colima "colima completion zsh"

# zoxide support
if command -v zoxide >>/dev/null; then
    _evalcache zoxide init zsh
fi
# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
