#!/bin/zsh
# CodeWhisperer pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.pre.zsh"

# Documentation: https://github.com/romkatv/zsh4humans/blob/v5/README.md.
zstyle ':z4h:' auto-update 'yes'
# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
zstyle ':z4h:' auto-update-days '14'

# Keyboard type: 'mac' or 'pc'.
zstyle ':z4h:bindkey' keyboard 'mac'

# Don't start tmux.
zstyle ':z4h:' start-tmux no

# Mark up shell's output with semantic information.
zstyle ':z4h:' term-shell-integration 'yes'

# Right-arrow key accepts one character ('partial-accept') from
# command autosuggestions or the whole thing ('accept')?
zstyle ':z4h:autosuggestions' forward-char 'partial-accept'

# Recursively traverse directories when TAB-completing files.
zstyle ':z4h:fzf-complete' recurse-dirs 'yes'

# Enable ('yes') or disable ('no') automatic teleportation of z4h over
# SSH when connecting to these hosts.
zstyle ':z4h:ssh:*.lunchb0ne.*' enable 'yes'
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*' enable 'no'

# Send these files over to the remote host when connecting over SSH to the
# enabled hosts.
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh' '~/.colors.zsh' '~/.alias.zsh'

# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `z4h init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
z4h install ohmyzsh/ohmyzsh || return                      # ohmyzsh as i use a few plugins from it
z4h install conda-incubator/conda-zsh-completion || return # 🐍 completions for conda & mamba
z4h install clarketm/zsh-completions || return             # a compliation of a lot of zsh completions
z4h install MichaelAquilina/zsh-you-should-use || return   # reminds me about aliases I've setup
z4h install mroth/evalcache || return                      # evalcache too
z4h install ellie/atuin || return                          # atuin shell history

# Install or update core components (fzf, zsh-autosuggestions, etc.) and
# initialize Zsh. After this point console I/O is unavailable until Zsh
# is fully initialized. Everything that requires user interaction or can
# perform network I/O must be done above. Everything else is best done below.
z4h init || return

# Source additional local environment files.
z4h source ~/.env.zsh

# Use additional Git repositories pulled in with `z4h install`.
z4h load ohmyzsh/ohmyzsh/plugins/git          # load git plugin
z4h load ohmyzsh/ohmyzsh/plugins/golang       # load go-lang plugin
z4h load ohmyzsh/ohmyzsh/plugins/vscode       # load vscode plugin
z4h load ohmyzsh/ohmyzsh/plugins/macos        # load macos plugin
z4h load ohmyzsh/ohmyzsh/plugins/composer     # load composer plugin
z4h load conda-incubator/conda-zsh-completion # load anaconda-completions
z4h load clarketm/zsh-completions             # load extended completions
z4h load MichaelAquilina/zsh-you-should-use   # load abbr reminders
z4h load mroth/evalcache                      # load eval chacher
z4h load ohmyzsh/ohmyzsh/plugins/magic-enter  # magic enter plugin
z4h load ellie/atuin                          # load atuin

z4h source ~/.alias.zsh  # load aliases
z4h source ~/.colors.zsh # load custom colors

# Define key bindings.
z4h bindkey undo Ctrl+/ Shift+Tab # undo the last command line change
z4h bindkey redo Option+/         # redo the last undone command line change

z4h bindkey z4h-cd-back Shift+Left     # cd into the previous directory
z4h bindkey z4h-cd-forward Shift+Right # cd into the next directory
z4h bindkey z4h-cd-up Shift+Up         # cd into the parent directory
z4h bindkey z4h-cd-down Shift+Down     # cd into a child directory

# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots    # no special treatment for file names with a leading dot
setopt no_auto_menu # require an extra TAB press to open the completion menu

# External Loaders
completion_cacher chezmoi "chezmoi completion zsh"
completion_cacher docker "docker completion zsh"

# bind atuin search widget to ctrl+r
bindkey '^r' _atuin_search_widget
# zoxide support
_evalcache zoxide init zsh

# CodeWhisperer post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.post.zsh"
