[tools]
node = ["latest", "lts"]
bun = ["latest"]
python = ["3.13", "3"]
usage = "latest"
uv = "latest"

[settings]
experimental = true
auto_install = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
